FROM golang:1.23-alpine3.19 AS builder

RUN apk add --no-cache \
    build-base \
    gcc \
    git
ENV GOROOT=/usr/local/go
ENV GOPATH=/go
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin

WORKDIR /app
RUN git clone https://github.com/USACE/seed-generator.git
WORKDIR /app/seed-generator
RUN go mod download
RUN go mod tidy
RUN go build -o seed-generator


FROM alpine:3.19 AS prod

WORKDIR /app
COPY --from=builder /app/seed-generator/seed-generator .